# 依赖
要使用Akka Streams，请将模块添加到您的项目中：
```xml
<properties>
 <akka.version>2.6.10</akka.version> <scala.binary.version>2.13</scala.binary.version></properties>
<dependency>
 <groupId>com.typesafe.akka</groupId> <artifactId>akka-stream_${scala.binary.version}</artifactId> <version>${akka.version}</version></dependency>
```
# 介绍
当流中的算子失败时，这通常会导致整个流被拆除。 下游的每个算子都知道故障，每个上游的算子都看到了取消的消息。
在许多情况下，您可能希望避免流完全失败，这可以通过几种不同的方式来完成：
- 恢复以发出最终元素，然后在上游故障时正常完成流
- recoveryWithRetries创建一个新的上游，并在出现故障时从中开始消耗
- 退避后重新启动流的各个部分
- 对支持它的算子使用监督策略
除了这些用于错误处理的内置工具之外，一种常见的模式是将流包装在actor中，并让actor在发生故障时重新启动整个流。
# 记录错误
log()启用流的日志记录，这通常对于错误日志记录很有用。 当元素0通过map运算符时，以下流因ArithmeticException而失败，
```java
Source.from(Arrays.asList(-1, 0, 1))
 .map(x -> 1 / x) // throwing ArithmeticException: / by zero .log("error logging") .runWith(Sink.ignore(), system);```
并记录以下错误消息。
```console
[error logging] Upstream failed.
java.lang.ArithmeticException: / by zero
```
如果要控制每个元素，完成和失败的日志记录级别，可以在“记录流中”中找到更多详细信息。
# 恢复
恢复允许您发出最终元素，然后在上游故障时完成流。 通过PartialFunction确定应恢复哪些异常。 如果没有定义匹配项，则流失败。
如果要在故障时正常完成流，同时让下游知道发生故障，则恢复非常有用。
在恢复中引发异常将自动记录在ERROR级别上。
恢复中的更多详细信息
```java
Source.from(Arrays.asList(0, 1, 2, 3, 4, 5, 6))
 .map( n -> { // assuming `4` and `5` are unexpected values that could throw exception if (Arrays.asList(4, 5).contains(n)) throw new RuntimeException(String.format("Boom! Bad value found: %s", n)); else return n.toString(); }) .recover( new PFBuilder<Throwable, String>() .match(RuntimeException.class, Throwable::getMessage) .build()) .runForeach(System.out::println, system);```
这将输出：
```console
0
1
2
3                         // last element before failure
Boom! Bad value found: 4  // first element on failure
```
# 重试恢复
recoveryWithRetries允许您将新的上游替换故障的上游，最多恢复指定次数的流故障。
通过PartialFunction确定应恢复哪些异常。 如果没有定义匹配项，则流失败。
```java
Source<String, NotUsed> planB = Source.from(Arrays.asList("five", "six", "seven", "eight"));
Source.from(Arrays.asList(0, 1, 2, 3, 4, 5, 6))
 .map( n -> { if (n < 5) return n.toString(); else throw new RuntimeException("Boom!"); }) .recoverWithRetries( 1, // max attempts new PFBuilder().match(RuntimeException.class, ex -> planB).build()) .runForeach(System.out::println, system);```
这将输出：
```console
0
1
2
3
4
five
six
seven
eight
```
# 使用backoff算子延迟重启
Akka流提供了RestartSource，RestartSink和RestartFlow来实现所谓的指数退避监管策略，在算子失败或完成时重新启动算子，每次重新启动之间的时间间隔都越来越长。
当算子失败或完成操作时，此模式很有用，因为某些外部资源不可用，我们需要给它一些时间重新启动。有用的主要例子之一是当WebSocket连接由于HTTP服务器正在关闭而运行失败(可能是由于过载)而失败时。通过使用指数退避，我们避免进入紧密的重新连接循环，这既使HTTP服务器有一些时间来恢复，又避免了在客户端使用不必要的资源。
提到的各种重新启动形状都期望akka.stream.RestartSettings来配置重新启动行为。可配置参数为：
- minBackoff是基础流重新启动之前的初始持续时间
- maxBackoff限制了指数补偿
- randomFactor允许在退避计算之后添加随机延迟
- maxRestarts限制重新启动的总数
- maxRestartsWithin设置一个时间范围，在此时间范围内，对于maxRestarts，重新启动计入相同的总数
下面的代码片段显示了如何使用akka.stream.javadsl.RestartSource创建退避监管器，它将监督给定的Source。在这种情况下，源是由akka-http生成的服务器发送事件流。如果流在任何时候失败或完成，则将以3、6、12、24和最后30秒的增加间隔再次发出请求(此时，由于maxBackoff参数而将其保持上限)：
```java
Source<ServerSentEvent, NotUsed> eventStream =
 RestartSource.withBackoff( Duration.ofSeconds(3), // min backoff Duration.ofSeconds(30), // max backoff 0.2, // adds 20% "noise" to vary the intervals slightly 20, // limits the amount of restarts to 20 () -> // Create a source from a future of a source Source.fromSourceCompletionStage( // Issue a GET request on the event stream Http.get(system) .singleRequest(HttpRequest.create("http://example.com/eventstream")) .thenCompose( response -> // Unmarshall it to a stream of ServerSentEvents EventStreamUnmarshalling.fromEventStream() .unmarshall(response, materializer))));```
强烈建议使用randomFactor向退避间隔添加一些额外的方差，以免多个流在完全相同的时间点重新启动，例如，因为它们由于共享资源(例如 同一服务器关闭并在相同的配置间隔后重新启动。 通过为重新启动间隔添加额外的随机性，流将在稍有不同的时间点启动，从而避免了流量高峰冲击正在恢复的服务器或它们都需要联系的其他资源。
除非将其汇入接收器，否则上述RestartSource将永远不会终止。 与KillSwitch结合使用通常很方便，因此可以在需要时终止它：
```java
KillSwitch killSwitch =
 eventStream .viaMat(KillSwitches.single(), Keep.right()) .toMat(Sink.foreach(event -> System.out.println("Got event: " + event)), Keep.left()) .run(materializer);
doSomethingElse();
killSwitch.shutdown();
```
还可以使用akka.stream.javadsl.RestartSink和akka.stream.javadsl.RestartFlow监控接收器和数据流。 RestartSink取消时将重新启动，而当in端口取消，out端口完成或out端口发送错误时，RestartFlow将重新启动。
>注意
使用GraphStages时，应注意在RestartSource，RestartSink或RestartFlow内部有条件地传播终止信号的情况。
一个示例是默认值为eagerCancel = false的Broadcast运算符，其中某些出口用于副作用分支(不会通过合并(Merge)重新加入)。侧分支上的故障不会终止将不会重新启动的受监督流。相反，主分支上的故障可以触发重新启动，但会留下旧的侧分支运行实例。
在此示例中，应该将eagerCancel设置为true，或者，当仅使用单个分支时，也应将To或divertTo视为替代方案。
# 监督策略
>注意
支持监督策略的算子已明确记录在案，如果算子的文档中没有任何内容表明其遵守监督策略，则表示它失败而不是实施监督。
错误处理策略受actor监督策略的启发，但其语义已适应流处理领域。最重要的区别在于，监管不会自动应用于流运算符，而是每个运算符必须明确实现的内容。
对于许多算子而言，实施对监管策略的支持甚至可能没有任何意义，对于连接到外部技术的算子而言尤其如此，例如，如果立即尝试建立新的连接，则失败的连接仍可能会失败(请参阅重新启动以了解更多信息，对于这种情况)。
对于确实实施监督的算子，当通过使用属性实现流时，可以选择如何处理流元素处理中的异常的策略。
有三种方法可以处理应用程序代码中的异常：
- 停止-流失败完成。
- 恢复-元素被删除，流继续。
- 重新启动-重新启动算子后，元素将被删除，并且流将继续。重新启动算子意味着清除了任何累积状态。这通常是通过创建运算符的新实例来执行的。
默认情况下，停止策略用于所有异常，即，抛出异常时，流将失败完成。
```java
final Source<Integer, NotUsed> source =
 Source.from(Arrays.asList(0, 1, 2, 3, 4, 5)).map(elem -> 100 / elem);final Sink<Integer, CompletionStage<Integer>> fold =
 Sink.<Integer, Integer>fold(0, (acc, elem) -> acc + elem);final CompletionStage<Integer> result = source.runWith(fold, system);
// division by zero will fail the stream and the
// result here will be a CompletionStage failed with ArithmeticException
```
流的默认监督策略可以在complete上定义RunnableGraph。
```java
final Function<Throwable, Supervision.Directive> decider =
 exc -> { if (exc instanceof ArithmeticException) return Supervision.resume(); else return Supervision.stop(); };final Source<Integer, NotUsed> source =
 Source.from(Arrays.asList(0, 1, 2, 3, 4, 5)) .map(elem -> 100 / elem) .withAttributes(ActorAttributes.withSupervisionStrategy(decider));final Sink<Integer, CompletionStage<Integer>> fold = Sink.fold(0, (acc, elem) -> acc + elem);
final RunnableGraph<CompletionStage<Integer>> runnableGraph = source.toMat(fold, Keep.right());
final RunnableGraph<CompletionStage<Integer>> withCustomSupervision =
 runnableGraph.withAttributes(ActorAttributes.withSupervisionStrategy(decider));
final CompletionStage<Integer> result = withCustomSupervision.run(system);
// the element causing division by zero will be dropped
// result here will be a CompletionStage completed with 228
```
在这里您可以看到所有ArithmeticException都将继续处理，即导致导致被零除的元素被有效地删除了。
>注意
请注意，删除元素可能会导致带有循环的图中的死锁，如“图周期，活动性和死锁”中所述。
还可以为流的所有算子定义监管策略。
```java
final Function<Throwable, Supervision.Directive> decider =
 exc -> { if (exc instanceof ArithmeticException) return Supervision.resume(); else return Supervision.stop(); };final Flow<Integer, Integer, NotUsed> flow =
 Flow.of(Integer.class) .filter(elem -> 100 / elem < 50) .map(elem -> 100 / (5 - elem)) .withAttributes(ActorAttributes.withSupervisionStrategy(decider));final Source<Integer, NotUsed> source = Source.from(Arrays.asList(0, 1, 2, 3, 4, 5)).via(flow);
final Sink<Integer, CompletionStage<Integer>> fold =
 Sink.<Integer, Integer>fold(0, (acc, elem) -> acc + elem);final CompletionStage<Integer> result = source.runWith(fold, system);
// the elements causing division by zero will be dropped
// result here will be a Future completed with 150
```
重新启动的工作方式与恢复相同，不同之处在于，将重置失败的处理算子的累积状态(如果有)。
```java
final Function<Throwable, Supervision.Directive> decider =
 exc -> { if (exc instanceof IllegalArgumentException) return Supervision.restart(); else return Supervision.stop(); };final Flow<Integer, Integer, NotUsed> flow =
 Flow.of(Integer.class) .scan( 0, (acc, elem) -> { if (elem < 0) throw new IllegalArgumentException("negative not allowed"); else return acc + elem; }) .withAttributes(ActorAttributes.withSupervisionStrategy(decider));final Source<Integer, NotUsed> source = Source.from(Arrays.asList(1, 3, -1, 5, 7)).via(flow);
final CompletionStage<List<Integer>> result =
 source.grouped(1000).runWith(Sink.<List<Integer>>head(), system);// the negative element cause the scan stage to be restarted,
// i.e. start from 0 again
// result here will be a Future completed with List(0, 1, 4, 0, 5, 12)
```
## 来自mapAsync的错误
流监管也可以应用于mapAsync和mapAsyncUnordered的future，即使此类失败发生在将来而不是在算子内部。
假设我们使用外部服务来查找电子邮件地址，而我们希望丢弃这些电子邮件地址。
我们从作者的推文流开始：
```java
final Source<Author, NotUsed> authors =
 tweets.filter(t -> t.hashtags().contains(AKKA)).map(t -> t.author);```
假设我们可以使用以下方法查找他们的电子邮件地址：
```java
public CompletionStage<String> lookupEmail(String handle)
```
如果未找到电子邮件，则CompletionStage将正常完成。
可以使用mapAsync通过使用lookupEmail服务将作者流转换为电子邮件地址流，并且我们使用Supervision.getResumingDecider删除未知的电子邮件地址：
```java
final Attributes resumeAttrib =
 ActorAttributes.withSupervisionStrategy(Supervision.getResumingDecider());final Flow<Author, String, NotUsed> lookupEmail =
 Flow.of(Author.class) .mapAsync(4, author -> addressSystem.lookupEmail(author.handle)) .withAttributes(resumeAttrib);final Source<String, NotUsed> emailAddresses = authors.via(lookupEmail);
```
如果我们不使用Resume，则默认的停止策略将在异常完成的第一个CompletionStage上以失败的方式完成流。